liquibase:
  enable: true


spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/To-Do
    username: postgres
    password: test@1234
  jpa:
    properties:
      hibernate:
        format-sql: true
      temp:
        use_jdbc_metadata_defaults : false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/master-changelog.xml

server:
  port: 9999









